import { getCountries } from "./get-countries";
import { languages } from "./languages";
import { getColor } from "./get-colors";
import { colors } from "./colors";
import { separatedCommas } from "./separated-commas";
import { initialValues } from "./initial-values-register";
import { getTotal } from "./get-total";
import { initialValuesIncomes } from "./initial-values-incomes";
import { initialValuesLogin } from "./initial-values-login";
import { getTotalMonth } from "./get-month-data";
import { getTotalYear } from "./get-total-year";
import { getResponsive } from "./get-screen";
import { getTotalDay } from "./get-total-day";
import { getTotalData } from "./get-total-data";

export { getCountries };
export { languages };
export { getColor };
export { colors };
export { separatedCommas };
export { initialValues };
export { getTotal };
export { initialValuesIncomes };
export { initialValuesLogin };
export { getTotalMonth };
export { getTotalYear };
export { getResponsive };
export { getTotalDay };
export { getTotalData };
